// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: rmm/v1/agent.proto

package rmmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandKind int32

const (
	CommandKind_COMMAND_KIND_UNSPECIFIED       CommandKind = 0
	CommandKind_COMMAND_KIND_SCRIPT            CommandKind = 1
	CommandKind_COMMAND_KIND_PACKAGE_INSTALL   CommandKind = 2
	CommandKind_COMMAND_KIND_PACKAGE_REMOVE    CommandKind = 3
	CommandKind_COMMAND_KIND_INVENTORY_REFRESH CommandKind = 4
	CommandKind_COMMAND_KIND_SELF_UNINSTALL    CommandKind = 5
)

// Enum value maps for CommandKind.
var (
	CommandKind_name = map[int32]string{
		0: "COMMAND_KIND_UNSPECIFIED",
		1: "COMMAND_KIND_SCRIPT",
		2: "COMMAND_KIND_PACKAGE_INSTALL",
		3: "COMMAND_KIND_PACKAGE_REMOVE",
		4: "COMMAND_KIND_INVENTORY_REFRESH",
		5: "COMMAND_KIND_SELF_UNINSTALL",
	}
	CommandKind_value = map[string]int32{
		"COMMAND_KIND_UNSPECIFIED":       0,
		"COMMAND_KIND_SCRIPT":            1,
		"COMMAND_KIND_PACKAGE_INSTALL":   2,
		"COMMAND_KIND_PACKAGE_REMOVE":    3,
		"COMMAND_KIND_INVENTORY_REFRESH": 4,
		"COMMAND_KIND_SELF_UNINSTALL":    5,
	}
)

func (x CommandKind) Enum() *CommandKind {
	p := new(CommandKind)
	*p = x
	return p
}

func (x CommandKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rmm_v1_agent_proto_enumTypes[0].Descriptor()
}

func (CommandKind) Type() protoreflect.EnumType {
	return &file_rmm_v1_agent_proto_enumTypes[0]
}

func (x CommandKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandKind.Descriptor instead.
func (CommandKind) EnumDescriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_SUCCEEDED   CommandStatus = 1
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 2
	CommandStatus_COMMAND_STATUS_TIMEOUT     CommandStatus = 3
	CommandStatus_COMMAND_STATUS_EXPIRED     CommandStatus = 4
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_SUCCEEDED",
		2: "COMMAND_STATUS_FAILED",
		3: "COMMAND_STATUS_TIMEOUT",
		4: "COMMAND_STATUS_EXPIRED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_SUCCEEDED":   1,
		"COMMAND_STATUS_FAILED":      2,
		"COMMAND_STATUS_TIMEOUT":     3,
		"COMMAND_STATUS_EXPIRED":     4,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rmm_v1_agent_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_rmm_v1_agent_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{1}
}

type UpdatePhase int32

const (
	UpdatePhase_UPDATE_PHASE_UNSPECIFIED UpdatePhase = 0
	UpdatePhase_UPDATE_PHASE_DOWNLOADING UpdatePhase = 1
	UpdatePhase_UPDATE_PHASE_VERIFIED    UpdatePhase = 2
	UpdatePhase_UPDATE_PHASE_APPLIED     UpdatePhase = 3
	UpdatePhase_UPDATE_PHASE_ROLLED_BACK UpdatePhase = 4
	UpdatePhase_UPDATE_PHASE_FAILED      UpdatePhase = 5
)

// Enum value maps for UpdatePhase.
var (
	UpdatePhase_name = map[int32]string{
		0: "UPDATE_PHASE_UNSPECIFIED",
		1: "UPDATE_PHASE_DOWNLOADING",
		2: "UPDATE_PHASE_VERIFIED",
		3: "UPDATE_PHASE_APPLIED",
		4: "UPDATE_PHASE_ROLLED_BACK",
		5: "UPDATE_PHASE_FAILED",
	}
	UpdatePhase_value = map[string]int32{
		"UPDATE_PHASE_UNSPECIFIED": 0,
		"UPDATE_PHASE_DOWNLOADING": 1,
		"UPDATE_PHASE_VERIFIED":    2,
		"UPDATE_PHASE_APPLIED":     3,
		"UPDATE_PHASE_ROLLED_BACK": 4,
		"UPDATE_PHASE_FAILED":      5,
	}
)

func (x UpdatePhase) Enum() *UpdatePhase {
	p := new(UpdatePhase)
	*p = x
	return p
}

func (x UpdatePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_rmm_v1_agent_proto_enumTypes[2].Descriptor()
}

func (UpdatePhase) Type() protoreflect.EnumType {
	return &file_rmm_v1_agent_proto_enumTypes[2]
}

func (x UpdatePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePhase.Descriptor instead.
func (UpdatePhase) EnumDescriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{2}
}

// Envelope is the single message type exchanged over the persistent
// agent<->gateway WebSocket connection. Every frame is one Envelope.
//
// Delivery semantics: commands are at-least-once. Every server-initiated
// message carries a unique message_id; agents must treat command
// redelivery as idempotent (journal of executed command IDs) and ack
// every message they act on.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID of this message, used for acks and idempotency.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// For acks/results: the message_id this responds to.
	InReplyTo string `protobuf:"bytes,2,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_AuthChallenge
	//	*Envelope_AuthResponse
	//	*Envelope_Hello
	//	*Envelope_Heartbeat
	//	*Envelope_CommandResult
	//	*Envelope_ShellOutput
	//	*Envelope_UpdateStatus
	//	*Envelope_Ack
	//	*Envelope_HelloAck
	//	*Envelope_CommandRequest
	//	*Envelope_ShellStart
	//	*Envelope_ShellInput
	//	*Envelope_ShellResize
	//	*Envelope_ShellStop
	//	*Envelope_UpdateOffer
	//	*Envelope_Decommission
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_rmm_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuthChallenge() *AuthChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthChallenge); ok {
			return x.AuthChallenge
		}
	}
	return nil
}

func (x *Envelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *Envelope) GetShellOutput() *ShellData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShellOutput); ok {
			return x.ShellOutput
		}
	}
	return nil
}

func (x *Envelope) GetUpdateStatus() *UpdateStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *Envelope) GetCommandRequest() *CommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CommandRequest); ok {
			return x.CommandRequest
		}
	}
	return nil
}

func (x *Envelope) GetShellStart() *ShellStart {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShellStart); ok {
			return x.ShellStart
		}
	}
	return nil
}

func (x *Envelope) GetShellInput() *ShellData {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShellInput); ok {
			return x.ShellInput
		}
	}
	return nil
}

func (x *Envelope) GetShellResize() *ShellResize {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShellResize); ok {
			return x.ShellResize
		}
	}
	return nil
}

func (x *Envelope) GetShellStop() *ShellStop {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShellStop); ok {
			return x.ShellStop
		}
	}
	return nil
}

func (x *Envelope) GetUpdateOffer() *UpdateOffer {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_UpdateOffer); ok {
			return x.UpdateOffer
		}
	}
	return nil
}

func (x *Envelope) GetDecommission() *Decommission {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Decommission); ok {
			return x.Decommission
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_AuthChallenge struct {
	// connection authentication (first two frames of every connection)
	AuthChallenge *AuthChallenge `protobuf:"bytes,1001,opt,name=auth_challenge,json=authChallenge,proto3,oneof"` // server -> agent
}

type Envelope_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,1002,opt,name=auth_response,json=authResponse,proto3,oneof"` // agent -> server
}

type Envelope_Hello struct {
	// agent -> server
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,12,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type Envelope_ShellOutput struct {
	ShellOutput *ShellData `protobuf:"bytes,13,opt,name=shell_output,json=shellOutput,proto3,oneof"`
}

type Envelope_UpdateStatus struct {
	UpdateStatus *UpdateStatus `protobuf:"bytes,14,opt,name=update_status,json=updateStatus,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,15,opt,name=ack,proto3,oneof"`
}

type Envelope_HelloAck struct {
	// server -> agent
	HelloAck *HelloAck `protobuf:"bytes,30,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type Envelope_CommandRequest struct {
	CommandRequest *CommandRequest `protobuf:"bytes,31,opt,name=command_request,json=commandRequest,proto3,oneof"`
}

type Envelope_ShellStart struct {
	ShellStart *ShellStart `protobuf:"bytes,32,opt,name=shell_start,json=shellStart,proto3,oneof"`
}

type Envelope_ShellInput struct {
	ShellInput *ShellData `protobuf:"bytes,33,opt,name=shell_input,json=shellInput,proto3,oneof"`
}

type Envelope_ShellResize struct {
	ShellResize *ShellResize `protobuf:"bytes,34,opt,name=shell_resize,json=shellResize,proto3,oneof"`
}

type Envelope_ShellStop struct {
	ShellStop *ShellStop `protobuf:"bytes,35,opt,name=shell_stop,json=shellStop,proto3,oneof"`
}

type Envelope_UpdateOffer struct {
	UpdateOffer *UpdateOffer `protobuf:"bytes,36,opt,name=update_offer,json=updateOffer,proto3,oneof"`
}

type Envelope_Decommission struct {
	Decommission *Decommission `protobuf:"bytes,37,opt,name=decommission,proto3,oneof"`
}

func (*Envelope_AuthChallenge) isEnvelope_Payload() {}

func (*Envelope_AuthResponse) isEnvelope_Payload() {}

func (*Envelope_Hello) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

func (*Envelope_CommandResult) isEnvelope_Payload() {}

func (*Envelope_ShellOutput) isEnvelope_Payload() {}

func (*Envelope_UpdateStatus) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_HelloAck) isEnvelope_Payload() {}

func (*Envelope_CommandRequest) isEnvelope_Payload() {}

func (*Envelope_ShellStart) isEnvelope_Payload() {}

func (*Envelope_ShellInput) isEnvelope_Payload() {}

func (*Envelope_ShellResize) isEnvelope_Payload() {}

func (*Envelope_ShellStop) isEnvelope_Payload() {}

func (*Envelope_UpdateOffer) isEnvelope_Payload() {}

func (*Envelope_Decommission) isEnvelope_Payload() {}

// AuthChallenge is the first frame the server sends on a new
// connection: a random nonce the agent must sign to prove possession of
// the device private key. Connections are dropped if the response does
// not arrive promptly.
type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 32 random bytes, single use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_rmm_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// AuthResponse proves device identity: signature is Ed25519 over the
// challenge nonce using the key generated at enrollment.
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_rmm_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Hello is the first frame an agent sends after the connection is
// authenticated. It carries a state digest so the server can reconcile
// after reconnects.
type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os              string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch            string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname        string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Command IDs the agent has results buffered for (delivered next).
	PendingResultIds []string `protobuf:"bytes,6,rep,name=pending_result_ids,json=pendingResultIds,proto3" json:"pending_result_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_rmm_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetPendingResultIds() []string {
	if x != nil {
		return x.PendingResultIds
	}
	return nil
}

type HelloAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server time, lets agents detect clock skew for cert validation.
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Heartbeat interval the agent must use, in seconds.
	HeartbeatIntervalS uint32 `protobuf:"varint,2,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_rmm_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HelloAck) GetHeartbeatIntervalS() uint32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_rmm_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_rmm_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{6}
}

// CommandRequest instructs the agent to execute a job step. The agent
// must persist the command ID before execution so redelivery after a
// crash never runs the same command twice.
type CommandRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Kind      CommandKind            `protobuf:"varint,2,opt,name=kind,proto3,enum=rmm.v1.CommandKind" json:"kind,omitempty"`
	// Kind-specific payload (script body ref, package spec, ...),
	// serialized as JSON validated against the server-side schema.
	Spec []byte `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// After this time the agent must not start the command and reports
	// status EXPIRED instead.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	TimeoutS      uint32                 `protobuf:"varint,5,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_rmm_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandRequest) GetKind() CommandKind {
	if x != nil {
		return x.Kind
	}
	return CommandKind_COMMAND_KIND_UNSPECIFIED
}

func (x *CommandRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CommandRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CommandRequest) GetTimeoutS() uint32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status    CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=rmm.v1.CommandStatus" json:"status,omitempty"`
	ExitCode  int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Inline output, capped (default 1 MiB); overflow is truncated and
	// truncated=true is set.
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_rmm_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *CommandResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *CommandResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CommandResult) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// Remote shell frames are multiplexed over the same connection by
// session_id. All shell traffic is also recorded server-side.
type ShellStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStart) Reset() {
	*x = ShellStart{}
	mi := &file_rmm_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStart) ProtoMessage() {}

func (x *ShellStart) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStart.ProtoReflect.Descriptor instead.
func (*ShellStart) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ShellStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ShellData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellData) Reset() {
	*x = ShellData{}
	mi := &file_rmm_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellData) ProtoMessage() {}

func (x *ShellData) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellData.ProtoReflect.Descriptor instead.
func (*ShellData) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ShellData) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellResize) Reset() {
	*x = ShellResize{}
	mi := &file_rmm_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellResize) ProtoMessage() {}

func (x *ShellResize) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellResize.ProtoReflect.Descriptor instead.
func (*ShellResize) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ShellResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ShellResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ShellStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellStop) Reset() {
	*x = ShellStop{}
	mi := &file_rmm_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellStop) ProtoMessage() {}

func (x *ShellStop) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellStop.ProtoReflect.Descriptor instead.
func (*ShellStop) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ShellStop) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// UpdateOffer tells the agent a new signed release is available. The
// agent downloads over HTTPS, verifies sha256 AND the Ed25519 signature
// against its embedded trusted keys before swapping binaries.
type UpdateOffer struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Url     string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Sha256  string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// minisign/Ed25519 signature over the binary.
	Signature     []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOffer) Reset() {
	*x = UpdateOffer{}
	mi := &file_rmm_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOffer) ProtoMessage() {}

func (x *UpdateOffer) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOffer.ProtoReflect.Descriptor instead.
func (*UpdateOffer) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOffer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateOffer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateOffer) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *UpdateOffer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Phase         UpdatePhase            `protobuf:"varint,2,opt,name=phase,proto3,enum=rmm.v1.UpdatePhase" json:"phase,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_rmm_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateStatus) GetPhase() UpdatePhase {
	if x != nil {
		return x.Phase
	}
	return UpdatePhase_UPDATE_PHASE_UNSPECIFIED
}

func (x *UpdateStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Decommission tells the agent its identity has been revoked. The agent
// stops reconnecting and, if uninstall is true, removes itself.
type Decommission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uninstall     bool                   `protobuf:"varint,1,opt,name=uninstall,proto3" json:"uninstall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decommission) Reset() {
	*x = Decommission{}
	mi := &file_rmm_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decommission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decommission) ProtoMessage() {}

func (x *Decommission) ProtoReflect() protoreflect.Message {
	mi := &file_rmm_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decommission.ProtoReflect.Descriptor instead.
func (*Decommission) Descriptor() ([]byte, []int) {
	return file_rmm_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *Decommission) GetUninstall() bool {
	if x != nil {
		return x.Uninstall
	}
	return false
}

var File_rmm_v1_agent_proto protoreflect.FileDescriptor

const file_rmm_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x12rmm/v1/agent.proto\x12\x06rmm.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\a\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1e\n" +
	"\vin_reply_to\x18\x02 \x01(\tR\tinReplyTo\x12?\n" +
	"\x0eauth_challenge\x18\xe9\a \x01(\v2\x15.rmm.v1.AuthChallengeH\x00R\rauthChallenge\x12<\n" +
	"\rauth_response\x18\xea\a \x01(\v2\x14.rmm.v1.AuthResponseH\x00R\fauthResponse\x12%\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\r.rmm.v1.HelloH\x00R\x05hello\x121\n" +
	"\theartbeat\x18\v \x01(\v2\x11.rmm.v1.HeartbeatH\x00R\theartbeat\x12>\n" +
	"\x0ecommand_result\x18\f \x01(\v2\x15.rmm.v1.CommandResultH\x00R\rcommandResult\x126\n" +
	"\fshell_output\x18\r \x01(\v2\x11.rmm.v1.ShellDataH\x00R\vshellOutput\x12;\n" +
	"\rupdate_status\x18\x0e \x01(\v2\x14.rmm.v1.UpdateStatusH\x00R\fupdateStatus\x12\x1f\n" +
	"\x03ack\x18\x0f \x01(\v2\v.rmm.v1.AckH\x00R\x03ack\x12/\n" +
	"\thello_ack\x18\x1e \x01(\v2\x10.rmm.v1.HelloAckH\x00R\bhelloAck\x12A\n" +
	"\x0fcommand_request\x18\x1f \x01(\v2\x16.rmm.v1.CommandRequestH\x00R\x0ecommandRequest\x125\n" +
	"\vshell_start\x18  \x01(\v2\x12.rmm.v1.ShellStartH\x00R\n" +
	"shellStart\x124\n" +
	"\vshell_input\x18! \x01(\v2\x11.rmm.v1.ShellDataH\x00R\n" +
	"shellInput\x128\n" +
	"\fshell_resize\x18\" \x01(\v2\x13.rmm.v1.ShellResizeH\x00R\vshellResize\x122\n" +
	"\n" +
	"shell_stop\x18# \x01(\v2\x11.rmm.v1.ShellStopH\x00R\tshellStop\x128\n" +
	"\fupdate_offer\x18$ \x01(\v2\x13.rmm.v1.UpdateOfferH\x00R\vupdateOffer\x12:\n" +
	"\fdecommission\x18% \x01(\v2\x14.rmm.v1.DecommissionH\x00R\fdecommissionB\t\n" +
	"\apayload\"%\n" +
	"\rAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"I\n" +
	"\fAuthResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xc5\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12,\n" +
	"\x12pending_result_ids\x18\x06 \x03(\tR\x10pendingResultIds\"y\n" +
	"\bHelloAck\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x120\n" +
	"\x14heartbeat_interval_s\x18\x02 \x01(\rR\x12heartbeatIntervalS\"@\n" +
	"\tHeartbeat\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x05\n" +
	"\x03Ack\"\xc4\x01\n" +
	"\x0eCommandRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.rmm.v1.CommandKindR\x04kind\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\fR\x04spec\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\ttimeout_s\x18\x05 \x01(\rR\btimeoutS\"\xa8\x02\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.rmm.v1.CommandStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"S\n" +
	"\n" +
	"ShellStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\">\n" +
	"\tShellData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"T\n" +
	"\vShellResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"*\n" +
	"\tShellStop\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"o\n" +
	"\vUpdateOffer\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"i\n" +
	"\fUpdateStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x13.rmm.v1.UpdatePhaseR\x05phase\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\fDecommission\x12\x1c\n" +
	"\tuninstall\x18\x01 \x01(\bR\tuninstall*\xcc\x01\n" +
	"\vCommandKind\x12\x1c\n" +
	"\x18COMMAND_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COMMAND_KIND_SCRIPT\x10\x01\x12 \n" +
	"\x1cCOMMAND_KIND_PACKAGE_INSTALL\x10\x02\x12\x1f\n" +
	"\x1bCOMMAND_KIND_PACKAGE_REMOVE\x10\x03\x12\"\n" +
	"\x1eCOMMAND_KIND_INVENTORY_REFRESH\x10\x04\x12\x1f\n" +
	"\x1bCOMMAND_KIND_SELF_UNINSTALL\x10\x05*\xa0\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COMMAND_STATUS_SUCCEEDED\x10\x01\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x02\x12\x1a\n" +
	"\x16COMMAND_STATUS_TIMEOUT\x10\x03\x12\x1a\n" +
	"\x16COMMAND_STATUS_EXPIRED\x10\x04*\xb5\x01\n" +
	"\vUpdatePhase\x12\x1c\n" +
	"\x18UPDATE_PHASE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18UPDATE_PHASE_DOWNLOADING\x10\x01\x12\x19\n" +
	"\x15UPDATE_PHASE_VERIFIED\x10\x02\x12\x18\n" +
	"\x14UPDATE_PHASE_APPLIED\x10\x03\x12\x1c\n" +
	"\x18UPDATE_PHASE_ROLLED_BACK\x10\x04\x12\x17\n" +
	"\x13UPDATE_PHASE_FAILED\x10\x05B@Z>github.com/codex666-cenotaph/rmmagic/shared/rmmpb/rmm/v1;rmmpbb\x06proto3"

var (
	file_rmm_v1_agent_proto_rawDescOnce sync.Once
	file_rmm_v1_agent_proto_rawDescData []byte
)

func file_rmm_v1_agent_proto_rawDescGZIP() []byte {
	file_rmm_v1_agent_proto_rawDescOnce.Do(func() {
		file_rmm_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rmm_v1_agent_proto_rawDesc), len(file_rmm_v1_agent_proto_rawDesc)))
	})
	return file_rmm_v1_agent_proto_rawDescData
}

var file_rmm_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_rmm_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rmm_v1_agent_proto_goTypes = []any{
	(CommandKind)(0),              // 0: rmm.v1.CommandKind
	(CommandStatus)(0),            // 1: rmm.v1.CommandStatus
	(UpdatePhase)(0),              // 2: rmm.v1.UpdatePhase
	(*Envelope)(nil),              // 3: rmm.v1.Envelope
	(*AuthChallenge)(nil),         // 4: rmm.v1.AuthChallenge
	(*AuthResponse)(nil),          // 5: rmm.v1.AuthResponse
	(*Hello)(nil),                 // 6: rmm.v1.Hello
	(*HelloAck)(nil),              // 7: rmm.v1.HelloAck
	(*Heartbeat)(nil),             // 8: rmm.v1.Heartbeat
	(*Ack)(nil),                   // 9: rmm.v1.Ack
	(*CommandRequest)(nil),        // 10: rmm.v1.CommandRequest
	(*CommandResult)(nil),         // 11: rmm.v1.CommandResult
	(*ShellStart)(nil),            // 12: rmm.v1.ShellStart
	(*ShellData)(nil),             // 13: rmm.v1.ShellData
	(*ShellResize)(nil),           // 14: rmm.v1.ShellResize
	(*ShellStop)(nil),             // 15: rmm.v1.ShellStop
	(*UpdateOffer)(nil),           // 16: rmm.v1.UpdateOffer
	(*UpdateStatus)(nil),          // 17: rmm.v1.UpdateStatus
	(*Decommission)(nil),          // 18: rmm.v1.Decommission
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_rmm_v1_agent_proto_depIdxs = []int32{
	4,  // 0: rmm.v1.Envelope.auth_challenge:type_name -> rmm.v1.AuthChallenge
	5,  // 1: rmm.v1.Envelope.auth_response:type_name -> rmm.v1.AuthResponse
	6,  // 2: rmm.v1.Envelope.hello:type_name -> rmm.v1.Hello
	8,  // 3: rmm.v1.Envelope.heartbeat:type_name -> rmm.v1.Heartbeat
	11, // 4: rmm.v1.Envelope.command_result:type_name -> rmm.v1.CommandResult
	13, // 5: rmm.v1.Envelope.shell_output:type_name -> rmm.v1.ShellData
	17, // 6: rmm.v1.Envelope.update_status:type_name -> rmm.v1.UpdateStatus
	9,  // 7: rmm.v1.Envelope.ack:type_name -> rmm.v1.Ack
	7,  // 8: rmm.v1.Envelope.hello_ack:type_name -> rmm.v1.HelloAck
	10, // 9: rmm.v1.Envelope.command_request:type_name -> rmm.v1.CommandRequest
	12, // 10: rmm.v1.Envelope.shell_start:type_name -> rmm.v1.ShellStart
	13, // 11: rmm.v1.Envelope.shell_input:type_name -> rmm.v1.ShellData
	14, // 12: rmm.v1.Envelope.shell_resize:type_name -> rmm.v1.ShellResize
	15, // 13: rmm.v1.Envelope.shell_stop:type_name -> rmm.v1.ShellStop
	16, // 14: rmm.v1.Envelope.update_offer:type_name -> rmm.v1.UpdateOffer
	18, // 15: rmm.v1.Envelope.decommission:type_name -> rmm.v1.Decommission
	19, // 16: rmm.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	19, // 17: rmm.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	0,  // 18: rmm.v1.CommandRequest.kind:type_name -> rmm.v1.CommandKind
	19, // 19: rmm.v1.CommandRequest.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 20: rmm.v1.CommandResult.status:type_name -> rmm.v1.CommandStatus
	19, // 21: rmm.v1.CommandResult.started_at:type_name -> google.protobuf.Timestamp
	19, // 22: rmm.v1.CommandResult.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 23: rmm.v1.UpdateStatus.phase:type_name -> rmm.v1.UpdatePhase
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_rmm_v1_agent_proto_init() }
func file_rmm_v1_agent_proto_init() {
	if File_rmm_v1_agent_proto != nil {
		return
	}
	file_rmm_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_AuthChallenge)(nil),
		(*Envelope_AuthResponse)(nil),
		(*Envelope_Hello)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_CommandResult)(nil),
		(*Envelope_ShellOutput)(nil),
		(*Envelope_UpdateStatus)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_HelloAck)(nil),
		(*Envelope_CommandRequest)(nil),
		(*Envelope_ShellStart)(nil),
		(*Envelope_ShellInput)(nil),
		(*Envelope_ShellResize)(nil),
		(*Envelope_ShellStop)(nil),
		(*Envelope_UpdateOffer)(nil),
		(*Envelope_Decommission)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rmm_v1_agent_proto_rawDesc), len(file_rmm_v1_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rmm_v1_agent_proto_goTypes,
		DependencyIndexes: file_rmm_v1_agent_proto_depIdxs,
		EnumInfos:         file_rmm_v1_agent_proto_enumTypes,
		MessageInfos:      file_rmm_v1_agent_proto_msgTypes,
	}.Build()
	File_rmm_v1_agent_proto = out.File
	file_rmm_v1_agent_proto_goTypes = nil
	file_rmm_v1_agent_proto_depIdxs = nil
}
